name: zebra_printer_example
description: Example app for zebra_printer package
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  zebra_printer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
